name: Deploy to Public GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        PUBLIC_URL: .
        
    - name: Deploy to public repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        # You'll need to create a Personal Access Token and add it as a secret
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # Replace with your public repository name
        external_repository: snorkel-ai/zephyrus-hub-public
        publish_dir: ./build
        publish_branch: main
